version: '3.5'

services:
  nginx-server:
    restart: always
    build: ./nginx
    image: nginx-server
    links:
      - server-one
      - server-two
      - server-three
    container_name: nginx-server
    ports:
    - "8080:80"

  server-one:
    build: 
      context: ./server
    image: server-one
    links:
      - redis
    expose:
      - "8080"
    container_name: server-one
    environment:
      - NAME=One
  server-two:
    build: 
      context: ./server
    image: server-two
    links:
      - redis
    expose:
      - "8080"
    container_name: server-two
    environment:
      - NAME=Two
  server-three:
    build: 
      context: ./server
    image: server-three
    links:
      - redis
    expose:
      - "8080"
    container_name: server-three
    environment:
      - NAME=Three
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  